# Generated by Django 5.0.6 on 2024-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hemnath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('EmailSubject', models.CharField(max_length=200)),
                ('Client', models.CharField(max_length=200)),
                ('Attention', models.CharField(max_length=200)),
                ('SiteEng', models.CharField(max_length=200)),
                ('ApprovedBy', models.CharField(max_length=200)),
                ('registereddate', models.CharField(max_length=200)),
                ('ApprovedDate', models.CharField(max_length=200)),
                ('Approvedprice', models.CharField(max_length=200)),
                ('QuotationRef', models.CharField(max_length=200)),
                ('QTDate', models.CharField(max_length=200)),
                ('UBSNo', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('Descriptions', models.CharField(max_length=200)),
                ('AED', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('SRdate', models.CharField(max_length=200)),
                ('LPO', models.CharField(max_length=200)),
                ('LPORef', models.CharField(max_length=200)),
                ('InvoiceRef', models.CharField(max_length=200)),
                ('Invoice', models.CharField(max_length=200)),
                ('REMARK', models.CharField(max_length=200)),
                ('EmailLPO', models.CharField(max_length=200)),
                ('Note', models.CharField(max_length=200)),
            ],
        ),
    ]
