# Generated by Django 4.2 on 2024-06-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemnath',
            name='Status',
            field=models.CharField(blank=True, choices=[('work_completed', 'Work Completed -> LPO not yet received'), ('lpo_received', 'LPO received -> Work still pending'), ('not_invoiced', 'Not invoiced tasks'), ('invoiced', 'Invoiced tasks')], max_length=20, null=True),
        ),
    ]
