# Generated by Django 4.2 on 2024-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemapp', '0002_alter_hemnath_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemnath',
            name='registereddate',
            field=models.DateField(),
        ),
    ]
